##############################################################################
#                             Studio Collections                             #
#                 Created by Yozora, Bullmoose20, & Sohjiro                  #
#          EDITING THIS FILE MAY CAUSE PULLING NEW UPDATES TO FAIL           #
#            https://kometa.wiki/en/latest/defaults/both/studio              #
#                                                                            #
#                    MODIFIED FOR LOCAL/PERSONALIZED USE                     #
#          !! PERSONAL COPY BECAUSE I DON'T KNOW WHAT I'M DOING !!           #
##############################################################################

external_templates:
  default: templates
  template_variables:
    collection_section: "070"


dynamic_collections:
  Studio:
    type: studio
    title_format: <<key_name>>
    template:
      - smart_filter
      - shared
    template_variables:
      search_term:
        default: studio.is
      search_term2:
        20th Century Studios: studio
      search_value2:
        20th Century Studios: 20th Century
      image:
        default: studio/<<key_encoded>>
      translation_key:
        default: studio
      dynamic:
        default: true
    include:
      #### MOVIES & TV SHOWS ###############################################################################################
      - A24
      - Blumhouse Productions
      - DreamWorks Studios
      - DreamWorks Pictures
      - Illumination Entertainment
      - Lifetime
      - Marvel Studios
      - Nickelodeon Animation Studio
      - Pixar
      - Walt Disney Animation
      - Walt Disney Pictures
      - Walt Disney Productions
    addons:
      DreamWorks Studios:
        - DreamWorks
        - DreamWorks Animation
        - DreamWorks Animation Television
        - DreamWorks Classics
      Illumination Entertainment:
        - Illumination
        - Illumination Films
      Marvel Studios:
        - Marvel Enterprises
        - Marvel Entertainment
        - Marvel
      Pixar:
        - Pixar Animation Studios
      Walt Disney Productions:
        - Disney Television Animation
        - DisneyToon Studios
        - Walt Disney Animation Studios
        - Walt Disney Pictures
        - Walt Disney Productions
        - Silver Screen Partners II
      Walt Disney Pictures:
        - Disney
        - Walt Disney Pictures
        - Walt Disney Productions
    title_override:
      Walt Disney Productions: Walt Disney Animation
    collection_mode: hide


