######################################################
#             Labels Series with Status              #
#                No Collection Built                 #
######################################################
collections:

  Shows That Ended:
    plex_all: true
    filters:
      tmdb_status: ended
    item_label: "Status: Ended"
    build_collection: false

  Canceled Shows:
    plex_all: true
    filters:
      tmdb_status: canceled
    item_label: "Status: Canceled"
    build_collection: false


# EXAMPLE FOR COLLECTION
#  Shows That Ended:
#    sort_title: 01_<<collection_name>>
#    item_label: "Status: Ended"
#    filters:
#      tmdb_status: ended, canceled
#    summary: TV shows that aired their series finale and have ended.
#    build_collection: true
#    collection_mode: hide
#    collection_order: release.desc
#    sync_mode: sync
