collections:
  Disney TV Movies:
    trakt_list: https://trakt.tv/users/moonprism/lists/dcom-wonderful-world-of-disney
    collection_mode: hide_items
    collection_order: custom
    sync_mode: sync
    sort_title: "!071_Disney TV"
    url_poster: https://raw.githubusercontent.com/iverbyou/kometa-config/main/configs/assets/collection/DCOM.jpg
    summary: "A collection of Disney TV movies including Disney Channel Premiere Films, Disney Channel Original Movies, and The Wonderful World of Disney"
