collections:

  Disney TV Movies:
    trakt_list:
      - https://trakt.tv/users/megan_html/lists/disney-channel-original-movies-dcom-complete-list?sort=released,desc
      - https://trakt.tv/users/megan_html/lists/disney-channel-premiere-films-complete-list?sort=released,desc
      - https://trakt.tv/users/moonprism/lists/disney-abc-freeform-original-movies?sort=released,desc
    collection_mode: hide_items
    sync_mode: sync
    sort_title: "!072_DCOMs"
    url_poster: https://raw.githubusercontent.com/iverbyou/kometa-config/main/images/collection/DCOM25.jpg
    summary: "A collection of Disney made for TV movies including Disney Channel Premiere Films, Disney Channel Original Movies, The Wonderful World of Disney, ABC Family Original Movies, and Freeform Originals."


  CHICAGO ✶:
    trakt_list: https://trakt.tv/users/moonprism/lists/chicago
    smart_label: random
    collection_mode: hide
    sync_mode: sync
    sort_title: "!090_Chicago"
    url_poster: https://raw.githubusercontent.com/iverbyou/kometa-config/main/images/collection/Chicago.jpg
    summary: "A collection of films set in or filmed in Chicago (and probably the surrounding suburbs)"

