templates:
  Collection:
    tmdb_collection_details: <<tmdb>>
    collection_mode: hide
    collection_order: release
    sync_mode: sync


collections:
######################################################
#               Franchise Collections                #
######################################################
  John Wick:
    template: {name: Collection, tmdb: 404609}
  Jurassic Park:
    template: {name: Collection, tmdb: 328}

#HORROR
  A Nightmare on Elm Street:
    template: {name: Collection, tmdb: 8581}
  Final Destination:
    template: {name: Collection, tmdb: 8864}
  Halloween:
    template: {name: Collection, tmdb: 91361}
  Halloween (The Rob Zombie Films):
    template: {name: Collection, tmdb: 126209}
  Jeepers Creepers:
    template: {name: Collection, tmdb: 94899}
  Scream:
    template: {name: Collection, tmdb: 2602}
  The Conjuring:
    template: {name: Collection, tmdb: 313086}

#DISNEY
  Aladdin:
    template: {name: Collection, tmdb: 86027}
  The Santa Clause:
    template: {name: Collection, tmdb: 53159}
