collections:

  A24:    
    smart_filter:
      all:
        studio: A24
      sort_by: title.asc
    collection_mode: hide
    sort_title: "!070_A24"
    url_poster: https://raw.githubusercontent.com/iverbyou/kometa-config/main/configs/assets/studio/A24.jpg


  DreamWorks Animation:    
    smart_filter:
      all:
        studio: DreamWorks Animation,DreamWorks Animation Television
      sort_by: title.asc
    collection_mode: hide
    sort_title: "!070_DreamWorks Animation"
    url_poster: https://raw.githubusercontent.com/iverbyou/kometa-config/main/configs/assets/studio/DreamWorks.jpg


  Illumination Entertainment:    
    smart_filter:
      all:
        studio: Illumination,Illumination Films
      sort_by: title.asc
    collection_mode: hide
    sort_title: "!070_Illumination"
    url_poster: https://raw.githubusercontent.com/iverbyou/kometa-config/main/configs/assets/studio/Illumination.jpg


  Pixar:    
    smart_filter:
      all:
        studio: Pixar,Pixar Animation
        duration.gte: 60
      sort_by: title.asc
    collection_mode: hide
    sort_title: "!070_Pixar"
    url_poster: https://raw.githubusercontent.com/iverbyou/kometa-config/main/configs/assets/studio/Pixar.jpg


  Walt Disney Animation:
    smart_filter:
      all:
        genre: Animation
        studio: Disney Television Animation,DisneyToon Studios,Walt Disney Animation,Walt Disney Pictures,Walt Disney Productions,Silver Screen Partners II
        duration.gte: 60
        title.isnot: "Mufasa: The Lion King"
      sort_by: title.asc
    collection_mode: hide
    sort_title: "!070_Walt Disney Animation"
    url_poster: https://raw.githubusercontent.com/iverbyou/kometa-config/main/configs/assets/studio/Disney Animation.jpg


  Walt Disney Pictures:    
    smart_filter:
      all:
        studio: Walt Disney Pictures,Walt Disney Productions
        genre.not: Animation
      sort_by: title.asc
    collection_mode: hide
    sort_title: "!070_Walt Disney Pictures"
    url_poster: https://raw.githubusercontent.com/iverbyou/kometa-config/main/configs/assets/studio/Disney Pictures.jpg










