collections:

  A24:    
    smart_filter:
      all:
        studio: A24
        duration.gte: 60
      sort_by: title.asc
    collection_mode: hide
    sort_title: "!070_A24"


  DreamWorks Animation:    
    smart_filter:
      all:
        studio: DreamWorks Animation,DreamWorks Animation Television
        duration.gte: 60
      sort_by: title.asc
    collection_mode: hide
    sort_title: "!070_DreamWorks Animation"


  Illumination:    
    smart_filter:
      all:
        studio: Illumination,Illumination Films
        duration.gte: 60
      sort_by: title.asc
    collection_mode: hide
    sort_title: "!070_Illumination"


  Pixar:    
    smart_filter:
      all:
        studio: Pixar,Pixar Animation
        duration.gte: 60
      sort_by: title.asc
    collection_mode: hide
    sort_title: "!070_Pixar"


  Walt Disney Animation:
    smart_filter:
      all:
        genre: Animation
        studio: Disney Television Animation,DisneyToon Studios,Walt Disney Animation,Walt Disney Pictures,Walt Disney Productions,Silver Screen Partners II
        duration.gte: 60
      sort_by: title.asc
    collection_mode: hide
    sort_title: "!070_Walt Disney Animation"


  Walt Disney Pictures:    
    smart_filter:
      all:
        studio: Walt Disney Pictures,Walt Disney Productions
        genre.not: Animation
        duration.gte: 60
      sort_by: title.asc
    collection_mode: hide
    sort_title: "!070_Walt Disney Pictures"










