templates:
  Studio:
    collection_mode: hide
    collection_order: alpha
    sync_mode: sync

  Company:
    optional:
      - with_genre
      - without_genre
      - without_keywords
      - runtime_over
      - runtime_under
    tmdb_discover:
      with_companies: <<tmdb>>
      with_genres: <<with_genre>>
      without_genres: <<without_genre>>
      without_keywords: <<without_keywords>>
      with_runtime.gte: <<runtime_over>>
      with_runtime.lte: <<runtime_under>>
      with_original_language: en
      sort_by: <<sort>>
    collection_mode: hide
    collection_order: custom
    sync_mode: sync

collections:

######################################################
#              Studio/Company Collections            #
######################################################
  Amazon Originals:
    sort_title: +002_Amazon
    trakt_list: https://trakt.tv/users/k0meta/lists/amazon-originals
    url_poster: https://i.imgur.com/KIAxUkV.jpeg
    collection_mode: hide
    collection_order: alpha
    sync_mode: sync

  Disney+ Originals:
    sort_title: +002_Disney+
    trakt_list: https://trakt.tv/users/k0meta/lists/disney-originals
    url_poster: https://i.imgur.com/8O7AvCd.jpeg
    collection_mode: hide
    collection_order: alpha
    sync_mode: sync

  Hulu Originals:
    sort_title: +002_Hulu
    trakt_list: https://trakt.tv/users/k0meta/lists/hulu-originals
    url_poster: https://i.imgur.com/BfNH8XE.jpeg
    smart_label: random
    collection_mode: hide
    sync_mode: sync

  Netflix Originals:
    sort_title: +002_Netflix
    trakt_list: https://trakt.tv/users/k0meta/lists/netflix-originals
    url_poster: https://i.imgur.com/xAwg2Oc.jpeg
    collection_mode: hide
    collection_order: alpha
    sync_mode: sync

  Paramount+ Originals:
    sort_title: +002_Paramount
    trakt_list: https://trakt.tv/users/k0meta/lists/paramount-originals
    url_poster: https://i.imgur.com/pGZnYnQ.jpeg
    collection_mode: hide
    collection_order: alpha
    sync_mode: sync
