##############################################################################
#                             TEST TEST TEST
##############################################################################

    - default: universe
      template_variables:
        use_separator: false
        collection_mode: hide
        collection_order: release
        include:
        - avp
        - conjuring
        - dcu
        - marvel
        - mcu
        - star
        - mummy
        - wizard
        - xmen
        #url_poster: https:raw.githubusercontent.com/iverbyou/kometa-config/main/assets/universe/<<key>>.jpg


