collections:

######################################################
#                       BY GENRE                     #
######################################################
  Based on a True Story:
    sort_title: Based on a True Story
    mdblist_list: https://mdblist.com/lists/moonprism/tv-based-on-true-story
    collection_mode: hide
    sync_mode: sync
